#!/bin/sh
# Thanks to http://stackoverflow.com/questions/11203483/run-a-java-application-as-a-service-on-linux
# Author: PbxMan

# CONFIG START
# Move the mineboard-agent.jar to a dedicated directory (i.e. /opt/mineboard-agent/)
# and replace the path here:
PATH_TO_JAR=/opt/mineboard-agent/
AGENT_NAME=mineboard-agent-0.0.1-SNAPSHOT.jar
# CONFIG END

# Do not change
SERVICE_NAME=MineboardAgent
PID_NAME=mineboard-agent.pid
PID_PATH_NAME=$PATH_TO_JAR$PID_NAME

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
	cd "$PATH_TO_JAR"
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -jar $AGENT_NAME 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
	    cd "$PATH_TO_JAR"
            nohup java -jar $AGENT_NAME 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 
